#!/usr/bin/env python

from foldback.nagios.plugin import NagiosSNMPPlugin, NagiosPluginError

DESCRIPTION = """Check for FreeBSD OS updates

Nagios plugin to check for FreeBSD OS level updates against metadata from
updates.freebsd.org mirrors.

"""

plugin = NagiosSNMPPlugin(description=DESCRIPTION)
plugin.run()

